### ISSUE TITLE
install instructions on macOS: "cannot find ocamlfind in your path"

### ISSUE THREAD

**Issue by semorrison** [HoTT/Coq-HoTT#1021]
Following the instructions at https://github.com/HoTT/HoTT/blob/master/INSTALL.md on macOS, when we get to the `etc/install_coq.sh` step in the HoTT directory, it fails with the following output:

```
$ git submodule sync
Synchronizing submodule url for 'coq-HoTT'
Synchronizing submodule url for 'etc/coq-dpdgraph'
Synchronizing submodule url for 'etc/coq-scripts'
$ git submodule update --init --recursive
~/scratch/HoTT/coq-HoTT ~/scratch/HoTT ~/scratch/HoTT/etc ~/scratch/HoTT
$ ./configure -local 
Error: cannot find 'ocamlfind' in your path!
```
Please adjust your path or use the -ocamlfind option of ./configure
Configuration script failed!

**Comment by kalfsvag** [comment]
Just wanted to say that I have the exact same issue, trying to install on Linux Mint.

**Comment by mikeshulman** [comment]
Did ocamlfind get installed somewhere on your system and it's just missing from the path?  Or did it not get installed at all?

**Comment by mikeshulman** [comment]
Actually I can't square the commands you listed with the instructions at `INSTALL.md`.  I don't see anywhere in that file instructions to run `git submodule` or `configure -local`.

**Comment by kalfsvag** [comment]
Everything from install_coq_deps.sh is installed.

Tried installing ocaml-findlib, and now the error instead is

**Comment by kalfsvag** [comment]
Everything from install_coq_deps.sh is installed.

Tried installing ocaml-findlib, and now the error instead is 

> Your version of OCaml is 4.02.3.
> You need OCaml 4.05.0 or later.

When trying to update ocaml using apt-get, I only get the assertion that I have the latest version. . .

**Comment by mikeshulman** [comment]
Try installing ocaml with opam instead: #929.

**Comment by mseri** [comment]
@kalfsvag make sure to use opam2: https://opam.ocaml.org/doc/Install.html

**Comment by kalfsvag** [comment]
I have to admit I am terribly confused right now.

I have updated to opam2 and used it to install ocaml. 
Running "ocamlfind -v" says that "The program 'ocamlfind' is currently not installed."

Running "opam install ocamlfind" gives me
"Package ocamlfind is already installed (current version is 1.8.0)."

Does this mean that "it's just missing from the path"? What does that mean, and how can it be fixed?

**Comment by mseri** [comment]
Try to run `eval $(opam env)` before doing anyting

**Comment by kalfsvag** [comment]
Okay, I got it to work. I first had to update to opam2, then had to follow instructions from [here](http://www.ocaml.org/docs/install.html) to get a new enough version of ocaml, then install ocamlfind, and then etc/install_coq.sh worked. . . $(opam env) was also necessary at some point, but I do not remember when.

**Comment by mikeshulman** [comment]
Maybe someone could check out #1025 and see whether the instructions there work?

**Comment by Alizter** [comment]
I'm closing this as some good time has passed and tools have improved. I've seen people use the library on macos with no issues.
