### ISSUE TITLE
Get travis to run timing scripts

### ISSUE THREAD

**Issue by Alizter** [HoTT/Coq-HoTT#1114]
Can we create a travis job that can run the timing scripts? When we create a PR one of the things we would like to do is to see how it compares with master. Currently we have to run the script manually, which can change deepening whose machine it is running on. Getting travis to do this would standardize the timing changes somewhat and make it less work for us.

I would suggest comparing the timing of master with the timing of the PR merged. We should be able to pop into the travis job and quickly see the table generated.

**Comment by JasonGross** [comment]
I can have Travis display the timing table for the current PR if it doesn't already, but the Travis machines aren't reliable enough, in my experience, to see accuracy of more than +- 10% or 20%.  And although the absolute timing changes depending on the machine, I expect relative timing to be roughly the same across machines.

**Comment by Alizter** [comment]
@JasonGross This has been done now right?

**Comment by JasonGross** [comment]
Pull requests do not compare timing against master. We could have them do this though.

**Comment by JasonGross** [comment]
However, they do display the timing tables without any comparison

**Comment by Alizter** [comment]
@JasonGross It would be nice if we can have a job for PRs that compare their build against master.

**Comment by JasonGross** [comment]
Very belatedly, the options are:
- have each job also build master
- store the timing logs from master, either
  - on a branch, which makes them easy to fetch but we have to actively manage them
  - as artifacts, which makes lookup a bit hard
