### ISSUE TITLE
Similtaneous import in Analysis/Locator.v breaking typeclass search

### ISSUE THREAD

**Issue by Alizter** [HoTT/Coq-HoTT#1336]
Typeclass search seems to be broken by simultaneous import in #1277. Specifically [here](https://github.com/HoTT/HoTT/pull/1277#discussion_r435587415).

**Comment by abooij** [comment]
(To be clear: this was just when I was writing this, and I couldn't figure it out at the time. It may be that a simple Coq reinstall or upgrade or whatever may resolve this. Please try the easiest stuff first.)

**Comment by Alizter** [comment]
OK, I've been messing around with this. It seems that there is an issue with DProp that I haven't quite pinned down. In Analysis/Locator.v you can replace the imports with:
```coq
Require Import
        HoTT.Basics
        HoTT.DProp.
Require Import
        HoTT.BoundedSearch
        HoTT.Types.Universe
        HoTT.Types.Sum
        HoTT.Types.Arrow
        HoTT.Spaces.Finite
        HoTT.ExcludedMiddle
        HoTT.Classes.interfaces.abstract_algebra
        HoTT.Classes.interfaces.orders
        HoTT.Classes.interfaces.integers
        HoTT.Classes.interfaces.rationals
        HoTT.Classes.interfaces.naturals
        HoTT.Classes.interfaces.cauchy
        HoTT.Classes.interfaces.archimedean
        HoTT.Classes.interfaces.round
        HoTT.Classes.interfaces.naturals
        HoTT.Classes.implementations.peano_naturals
        HoTT.Classes.orders.orders
        HoTT.Classes.orders.archimedean
        HoTT.Classes.orders.rings
        HoTT.Classes.orders.dec_fields
        HoTT.Classes.orders.semirings
        HoTT.Classes.orders.lattices
        HoTT.Classes.theory.rings
        HoTT.Classes.theory.apartness
        HoTT.Classes.theory.rationals
        HoTT.Classes.orders.fields
        HoTT.Classes.theory.fields
        HoTT.Classes.theory.dec_fields.
```
Any everything works fine. But if you merge this into one import things begin to break. I will continue investigating why this is.

**Comment by Alizter** [comment]
There is some weird interaction between importing Basics and DProp.
