### ISSUE TITLE
library dependency graphs broken

### ISSUE THREAD

**Issue by JasonGross** [HoTT/Coq-HoTT#1488]
The new build system fixed the per-file dependency graphs but broke the whole-library dependency graphs at, e.g., https://hott.github.io/HoTT/dependencies/HoTTCore.svg

**Comment by ndea7941** [comment]
Hi, just wondering if the whole-library dependency graphs may have ended up in a new home in the time since the issue was originally posted? Thanks.

**Comment by Alizter** [comment]
@ndea7941 I've fixed this issue I believe. The correct links should all be in the wiki. If they are incorrect, please let me know.

**Comment by ndea7941** [comment]
> @ndea7941 I've fixed this issue I believe. The correct links should all be in the wiki. If they are incorrect, please let me know.

Thanks for that, you're right they are there now (https://github.com/HoTT/Coq-HoTT/wiki).
