### ISSUE TITLE
Test installation of HoTT library on MacOS / Windows by hand and through opam

### ISSUE THREAD

**Issue by Alizter** [HoTT/Coq-HoTT#1588]
Since the HoTT library gets distributed with the Coq Platform we should probably test that opam is able to install it on Windows on MacOS. The obvious thing to do would be to add CI jobs for this but this comes with some problems:
* We cannot use the coq-docker images for MacOS and Windows since only linux is supported.
* Building ocaml, coq and the library will take a long time and is probably not to useful for users of the CI. I can't imagine anybody wants to wait for an hour for their PR to be green.

So perhaps a better solution is to have a manual github hub action doing this, so we can occasionally check that builds are supported. This would be useful when we do releases of the library for releases of Coq.

Currently on a CI run we are building the library a total of 9 times. For each version of coq: supported, latest and dev. And we try opam, building by hand intending to be quick and building by hand together with documentation and timing. The latter is then used to generate and later deploy our documentation.

**Comment by JasonGross** [comment]
Also Fiat Crypto has a Mac job we can copy: https://github.com/mit-plv/fiat-crypto/blob/master/.github/workflows/coq-macos.yml and also a Windows job: https://github.com/mit-plv/fiat-crypto/blob/master/.github/workflows/coq-windows.yml

**Comment by Alizter** [comment]
I think ultimately our CI isn't about testing Coq on various platforms but making sure that the library compiles. If for whatever reason Coq doesn't work on other platforms that's something for Coq to check for and not us. Therefore I am closing this issue.
