### ISSUE TITLE
HITs in Spaces/No/Core.v might be inconsistent

### ISSUE THREAD

**Issue by jdchristensen** [HoTT/Coq-HoTT#1759]
The induction principle for a HIT needs to be written using an idiom that makes Coq think that the supporting arguments are used.  Otherwise one can prove inconsistencies.  #1758 fixes this for all HITs except the HITs in Space/No/Core.v, which will require a bit more thought.  Tagging @mikeshulman since it appears he knows that file best.

**Comment by mikeshulman** [comment]
Ugh, I don't have time to think about this right now, but I'll put it on the back burner.
