### ISSUE TITLE
Prove that `n / (m / k) = (n * k) / m`

### ISSUE THREAD

**Issue by Alizter** [HoTT/Coq-HoTT#2073]
We should be able to prove the following

```coq
Definition nat_div_div_r n m k : k < m -> n / (m / k) = (n * k) / m.
Proof.
  intros H.
  destruct (nat_zero_or_gt_zero k) as [[] | kp].
  1: by rewrite nat_mul_zero_r, nat_div_zero_l.
  destruct (nat_zero_or_gt_zero m) as [[] | mp].
  1: by rewrite nat_div_zero_l.
```

But I wasn't able to work out how to continue. It's not needed, but it would complement our other division lemmas nicely.

The condition `k < m` appear to be necessary since otherwise we would get `0` on the LHS.

_Originally posted by @Alizter in https://github.com/HoTT/Coq-HoTT/issues/2070#issuecomment-2323484342_

**Comment by jdchristensen** [comment]
> ```coq
> k < m -> n / (m / k) = (n * k) / m.
> ```
This isn't true.  E.g. with n = 1, m = 3 and k = 2, the LHS is 1 / (3 / 2) = 1 / 1 = 1 while the RHS is (1 * 2) / 3 = 0.

**Comment by Alizter** [comment]
Yes, I would say then the condition needs to be `(k | m)` instead.

**Comment by jdchristensen** [comment]
> Yes, I think the condition needs to be `(k | m)` instead.

With that condition, the proof is pretty easy.
