### ISSUE TITLE
Publish release compatible with Coq 8.20

### ISSUE THREAD

**Issue by SnarkBoojum** [HoTT/Coq-HoTT#2091]
(I'm trying to update the Coq packages in Debian, so I'm looking for a set of coherent upstream releases)

**Comment by Alizter** [comment]
I will cut a release after #2087 and some more thinking.

**Comment by Alizter** [comment]
@jdchristensen I'm thinking of cutting a release. Anything else that comes to mind that would be good to have for the 8.20 release. This will probably end up appearing in Coq Platform.

**Comment by jdchristensen** [comment]
Seems fine to me.  Thanks for handling it!

**Comment by Alizter** [comment]
I've done an 8.20 release compatible with 8.19-8.20 that you can target.
