### ISSUE TITLE
Table of contents ordering

### ISSUE THREAD

**Issue by JasonGross** [HoTT/Coq-HoTT#571]
For the [table of contents](http://hott.github.io/HoTT/coqdoc-html/toc.html), do we to put files like `Basics.v` before or after the contents of the directory?  I'm thinking before (it's what I eventually settled on for categories), because they're kind-of like meta-chapters.  The way to control this is by reordering the list of files in `Makefile_targets.mk`.

**Comment by Alizter** [comment]
There doesn't seem to be much consensus on this topic so closing.
