### ISSUE TITLE
Naming of predicates

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/Coq-HoTT#662]
In which cases should we prefix a predicate's name with `Is`?  We have `IsEquiv` and `IsTrunc`, where the `Is` is necessary to distinguish them from the sigma-type `Equiv` and the reflector `Trunc`.  I also used it for a similar reason in `IsIdempotent` and friends.  However, the first two cases are also hprops, whereas `IsIdempotent` is not.  Should we restrict `Is` to hprops?  If so, what convention can we use to distinguish the predicate "being an idempotent" from the sigma-type of idempotent functions?  If not, should we use it for _all_ predicates, so we would have also `IsWeaklyConstant` and `IsDecidable` and `IsDecidablePaths` (or more grammatically but less consistently, `HasDecidablePaths`)?

**Comment by Alizter** [comment]
I think eventually we settled on not restricting `Is` for hprop-valued predicates and opting for `HasBinaryProducts` when grammatically correct.
