### ISSUE TITLE
etc/install_coq.sh

### ISSUE THREAD

**Issue by spitters** [HoTT/Coq-HoTT#698]
```
$ make clean
make: *** No rule to make target `clean'.  Stop.
```

I am guessing this should just be removed from the script?

**Comment by JasonGross** [comment]
No, this is a bug in a makefile, I think.  I don't have time to investigate at the moment.  This comes up in Coq's makefile?

**Comment by spitters** [comment]
The very end of the install_coq.sh

**Comment by rcraigfiedorek** [comment]
Has this issue been fixed? I'm having the same problem.

**Comment by jkingdon** [comment]
If I follow the directions at https://github.com/HoTT/HoTT/blob/master/INSTALL.md (on Ubuntu 16.04.3 LTS using ./etc/install_coq_deps.sh), I get the `No rule to make target 'clean'` message about make check. 

Ignoring the message worked. Trying to fix it by messing around with autoconf and other attempted workarounds didn't seem to (sorry, don't have a log of exactly what I tried, but deleting everything and starting over was what eventually fixed it).

**Comment by JasonGross** [comment]
Oh, I see, the issue is that `make clean ` makes no sense if HoTT hasn't been configured yet.  The appropriate solution is to replace it with something like
``` 
find coq theories contrib -name "*.vo"  -exec rm {} \;
```

**Comment by Alizter** [comment]
We don't use a configure script any longer so `make clean` should work fine. This is also not an issue when building with dune.
