### ISSUE TITLE
Set SimplIsCbn

### ISSUE THREAD

**Issue by JasonGross** [HoTT/Coq-HoTT#709]
We should add the following to Overture:

``` coq
(** This command makes [simpl] more well-behaved.  For example, it makes [simpl] better at re-folding fixpoints and respecting [Arguments] commands. *)
Global Set SimplIsCbn.
```

However, it currently breaks some files.  The current breakage is:

```
$ make -j16 -k
HOQC theories/categories/NaturalTransformation/Composition/Laws
HOQC theories/categories/Adjoint/UniversalMorphisms/Core
HOQC theories/Modalities/Modality
HOQC theories/categories/CategoryOfSections/Core
File "./theories/categories/NaturalTransformation/Composition/Laws.v", line 23, characters 2-6:
Error: Attempt to save an incomplete proof
make: *** [theories/categories/NaturalTransformation/Composition/Laws.vo] Error 1
File "./theories/categories/CategoryOfSections/Core.v", line 49, characters 4-310:
Error: Proof is not complete.
make: *** [theories/categories/CategoryOfSections/Core.vo] Error 1
File "./theories/Modalities/Modality.v", line 309, characters 69-71:
Error:
In environment
O : Modality
A, B : Type
A_inO : In O A
f : A -> B
feq : IsEquiv f
x : O_reflector O B
a : B
Unable to unify "to O B" with
 "O_indO O (O_reflector O B)
    (fun _ : Os.O_reflector O (O_reflector O B) => B) idmap".
make: *** [theories/Modalities/Modality.vo] Error 1
File "./theories/categories/Adjoint/UniversalMorphisms/Core.v", line 91, characters 6-77:
Error:
Found no subterm matching "IsInitialMorphism_property_morphism
                             ?M1054 ?M1055 ?M1056" in the current goal.
make: *** [theories/categories/Adjoint/UniversalMorphisms/Core.vo] Error 1
make: Target `all' not remade because of errors.
```

I believe the first two are due to [bug 3988](https://coq.inria.fr/bugs/show_bug.cgi?id=3988).

**Comment by mikeshulman** [comment]
In `Modality`, I don't know why `cbn` is unfolding `O_ind_internal` on that line while `simpl` wasn't.  However, it seems that neither of them is necessary anyway; presumably something else has changed somewhere since that proof was written.

**Comment by Alizter** [comment]
I don't quite understand what simpl does compared to cbn. I have read time and time again that cbn is "better behaved" but sometimes I have found that simpl does what I want better than cbn does. If we could understand exactly which reductions are being applied that would help alot.

**Comment by JasonGross** [comment]
Given that [the response of the coq-devs](https://github.com/coq/coq/issues/3988#issuecomment-337530357) to coq/coq#3988 is
> The the end of my command on [BZ#3989](https://github.com/coq/coq/issues?q=is%3Aissue%20%22Original%20bug%20ID%3A%20BZ%233989%22). I pretend that cbn is right !

See also coq/coq#7674, coq/coq#3989, and [many others](https://github.com/coq/coq/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+cbn+simpl).  It's not clear to me that anone has a clear picture of the differences between `simpl` and `cbn`?

**Comment by Alizter** [comment]
Sometimes I feel like simpl is clever enough not to reduce things down too much and get messy, wheras cbn just reduces everything until it hits a simpl nomatch.

This discussion would probably benefit from some examples, which I can't be bothered to give right now.

**Comment by JasonGross** [comment]
> Sometimes I feel like simpl is clever enough not to reduce things down too much and get messy, wheras cbn just reduces everything until it hits a simpl nomatch.

Indeed.  On the other hand, `simpl` will sometimes leave over beta redexes, as in
```coq
Record foo := { bar : Type }.
Definition baz (x : Type) := x.
Arguments baz / : simpl nomatch.
Goal forall x, baz match x with Build_foo bar0 => bar0 end.
  simpl.
(*   forall x : foo,
  (fun x0 : Type => x0) match x with
                        | {| bar := bar0 |} => bar0
                        end
*)
```
(c.f. https://github.com/coq/coq/issues/3989#issuecomment-337530374)

**Comment by Alizter** [comment]
Is there any advantage to restricting the behaviour of `simpl` if we already have `cbn`? Wouldn't it be better just to leave both and use whatever is better. That appears to be the defacto practice in Coq anyway. If you feel otherwise please reopen.

**Comment by jdchristensen** [comment]
I definitely agree that having both behaviours is useful.  I can't predict in a given situation which is best, but often one is better than the other, so I wouldn't want to lose the current `simpl` behaviour.  In fact, if I could only have one, I'd choose `simpl`.
