### ISSUE TITLE
Lemma for commuting `ap` and `transportD`

### ISSUE THREAD

**Issue by JasonGross** [HoTT/Coq-HoTT#732]
Is this lemma in the library?  Is it a specialized version of something in the library?  Where should it go?  (PathGroupoids?)  Is there a better name for it?

``` coq
Lemma ap_transportD_commute {A} B (CT : Type) (C1 C2 : forall a : A, B a -> CT) {x1 x2}
      (p : x1 = x2) y {D} (f : CT -> D) (H : C1 x1 y = C2 x1 y)
: ap f (transportD B (fun a b => C1 a b = C2 a b) p y H)
  = transportD B (fun a b => f (C1 a b) = f (C2 a b)) p y (ap f H).
Proof.
  destruct p; simpl; reflexivity.
Defined.
```

**Comment by mikeshulman** [comment]
Could it be a generalized version of something that exists for `transport`?

**Comment by Alizter** [comment]
I suppose if this is needed it can always be added, however I have yet to see a need for it so closing.
