### ISSUE TITLE
Switch to the new unification algorithm

### ISSUE THREAD

**Issue by spitters** [HoTT/Coq-HoTT#734]
@mattam82, @beta-ziliani have implemented a sane unification algorithm.
https://github.com/unicoq/unicoq
https://www.mpi-sws.org/~beta/unicoq.pdf

We probably want to switch at some point when we are frustrated with incomprehensible unification errors.

**Comment by mikeshulman** [comment]
Is it planned to be integrated into Coq trunk?

**Comment by spitters** [comment]
That's my understanding.
We should probably wait until it gets moved to trunk, but I wanted to
record the fact that it's there.

**Comment by andrejbauer** [comment]
Or we could be on the bleeding edge. I heard from the Coq developers that @JasonGross alone provides enough work for them. (I am kidding, let's wait until it gets into trunk.)

**Comment by spitters** [comment]
The algorithm already works on stdlib, cpdt and math-comp.
Testing it on HoTT would probably be interesting, but I will wait a bit
before doing it myself.

**Comment by ejgallego** [comment]
For the record, I tested it some weeks ago, and it seems it is still lacking lots of "unification power" to get within range of compiling HoTT.

**Comment by beta-ziliani** [comment]
It's a nice test case for future additions to the algorithm. I hope to get a student to work on it at some point...

**Comment by Alizter** [comment]
Looks like this isn't happening upstream at any point so no use holding our breath here.
