### ISSUE TITLE
Universe Comparator

### ISSUE THREAD

**Issue by spitters** [HoTT/Coq-HoTT#769]
This plugin allows to debug universe polymorphism. It may be useful.
https://github.com/amintimany/UniverseComparator

**Comment by mikeshulman** [comment]
Interesting!  Does it give any information that isn't visible with `Set Printing Universes.  About foo.`?

**Comment by JasonGross** [comment]
Nothing that isn't derivable, but I think it lets you query the relation between particular universes, so you don't have to perform the transitive closure operation mentally.

**Comment by mikeshulman** [comment]
Seems nice.  We could add a remark about it somewhere in `STYLE.md` maybe?

**Comment by Alizter** [comment]
In more recent version of Coq, it has been possible to see universes and the relations between them at any given point with:
```
Show Universes.
```
https://coq.inria.fr/doc/V8.18.0/refman/proofs/writing-proofs/proof-mode.html#coq:cmd.Show-Universes

**Comment by SkySkimmer** [comment]
Show Universes is from Coq 8.5 AFAICT
