### ISSUE TITLE
bug with type-in-type?

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/Coq-HoTT#965]
Consider the following code:

```coq
Definition foo {X : Type} (f : X -> X) := True.
Definition E := { p : forall X, X & True }.
Definition e : E -> E := fun x => projT1 x E.
Definition bar : foo e := I.
```

In ordinary Coq this unsurprisingly gives a universe inconsistency, but (again unsurprisingly) under `-type-in-type` it works fine.  However, if the HoTT library is also loaded (with `-coqlib` only, no `Require` statements are needed), then even under `-type-in-type` it gives the error 

```
The term "e" has type
 "E@{Test.25 Test.21 Test.26} -> E@{Test.22 Test.23 Test.24}"
while it is expected to have type
 "E@{Test.25 Test.21 Test.26} -> E@{Test.25 Test.21 Test.26}"
(cannot unify "E@{Test.22 Test.23 Test.24}" and
"E@{Test.25 Test.21 Test.26}").
```

which does not seem like what should happen --- `-type-in-type` should suppress all universe-checking, shouldn't it?

I figure I should report this as a Coq bug, but I'd like to be able to tell the devs what exactly it is about the HoTT library that causes this.  It has something to do with the context in which `sig` is defined in the HoTT library, because if I simply redefine `sig` at the top of the problematic code then it works fine.  But I've tried also copying in all the `Set` options from the HoTT library that I can find (universe polymorphism, asymmetric patterns, primitive projections, nonrecursive elimination schemes) and that's not enough to make it break.  Any ideas?

**Comment by Alizter** [comment]
Did you manage to work out what was causing this?

**Comment by mikeshulman** [comment]
No.

**Comment by Alizter** [comment]
I don't think there is much we can do about this here. I tried reproducing this some years back but had no success.
